name: API and UI Test Pipeline

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
  pull_request:
    branches:
      - CI/CDSolution
  schedule:
    - cron: '0 3 * * *'

jobs:
  api-tests:
    name: Run API Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore AutomatedTestingPracticalTaskEPAM.sln

      - name: Run API Tests
        run: |
          dotnet test ./LocatorsTests/Tests.csproj \
          --filter "Category=APITests" \
          --logger "trx;LogFileName=ApiTests.trx" \
          --no-restore --no-build
        continue-on-error: true

      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Results
          path: '**/TestResults/'

  ui-tests:
    name: Run UI Tests
    runs-on: windows-latest
    needs: api-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore AutomatedTestingPracticalTaskEPAM.sln

      - name: Run UI Tests
        run: |
          dotnet test ./LocatorsTests/Tests.csproj \
          --filter "Category=UITests" \
          --logger "trx;LogFileName=ApiTests.trx" \
          --no-restore --no-build
            -- TestRunParameters.Parameter(name="browser",value="${{ github.event.inputs.browser }}")

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: UI-Test-Results
          path: '**/TestResults/'

      - name: Upload Screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: UI-Screenshots
          path: '**/Screenshots'
